# from https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
# FIXME: enable dist-mode
matrix:
    include:
        - name: "Linux-Py3"
          os: linux
          env:
            - MINICONDA=Miniconda3-latest-Linux-x86_64.sh
        - name: "OsX-Py3"
          os: osx
          osx_image: xcode12
          compiler:
            - gcc
          env:
            - MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh
            - MACOSX_DEPLOYMENT_TARGET=10.9

install:
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n CB python=3.7 conda-build
  - source activate CB
  # Useful for debugging any issues with conda
  - conda info -a
  - gcc -v
  - g++ -v

script:
  - conda build -c intel -c conda-forge --numpy=1.17 --output-folder ./ conda-recipe
