matrix:
    include:
        - name: "Linux-Py3"
          os: linux
          env:
            - MINICONDA=Miniconda3-latest-Linux-x86_64.sh

install:
  - wget https://repo.continuum.io/miniconda/$MINICONDA -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n CB python=3.7 conda-build
  - source activate CB
  # Useful for debugging any issues with conda
  - conda info -a
  - gcc -v
  - g++ -v

script:
  - conda build -c intel -c conda-forge --numpy=1.17 --output-folder ./ conda-recipe
